export const PLANS = {
  trial: {
    slug: 'trial',
    name: 'Trial',
    monthlyPrice: 0,
    annualPrice: 0,
    monthlyPriceUSD: 0,
    annualPriceUSD: 0,
    clickLimit: -1,
    siteLimit: -1,
    retentionDays: 7,
    features: ['CAPI Facebook'],
    featuresEN: ['Facebook CAPI'],
  },
  starter: {
    slug: 'starter',
    name: 'Starter',
    monthlyPrice: 79,
    annualPrice: 55,
    monthlyPriceUSD: 19,
    annualPriceUSD: 13,
    clickLimit: 10000,
    siteLimit: 3,
    retentionDays: 7,
    features: ['CAPI Facebook, Google e TikTok', 'Relatórios de UTM e horário', 'Portal do cliente'],
    featuresEN: ['Facebook, Google & TikTok CAPI', 'UTM & time reports', 'Client portal'],
  },
  pro: {
    slug: 'pro',
    name: 'Pro',
    monthlyPrice: 179,
    annualPrice: 119,
    monthlyPriceUSD: 49,
    annualPriceUSD: 33,
    clickLimit: 50000,
    siteLimit: 15,
    retentionDays: 30,
    features: ['Tudo do Starter', 'Múltiplos pixels por site', 'Webhooks', 'Pixels adicionais do Facebook'],
    featuresEN: ['Everything in Starter', 'Multiple pixels per site', 'Webhooks', 'Additional Facebook pixels'],
  },
  agency: {
    slug: 'agency',
    name: 'Agency',
    monthlyPrice: 349,
    annualPrice: 229,
    monthlyPriceUSD: 99,
    annualPriceUSD: 69,
    clickLimit: 200000,
    siteLimit: -1,
    retentionDays: 180,
    features: ['Tudo do Pro', 'Sites ilimitados', 'Suporte prioritário'],
    featuresEN: ['Everything in Pro', 'Unlimited sites', 'Priority support'],
  },
};

export function getPlan(slug) {
  return PLANS[slug] || PLANS.trial;
}
